/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.obsidianchain;

import com.obsidianchain.components.*;
import com.obsidianchain.utilities.*;
import com.google.gson.GsonBuilder;
import java.util.ArrayList;
import java.security.Security;
import java.util.Base64;
import java.util.HashMap;

public class ObsidianChain {
    public final static int DIFFICULTY = 5;
    public final static float minimumTransaction = 2f;
    public static ArrayList<Block> blockchain = new ArrayList<Block>();

    //Keeps track of unspent coins
    public static HashMap<String, TransactionOutput> UTXOs = new HashMap<String, TransactionOutput>();

    private static Wallet walletA;
    private static Wallet walletB;

    public String getGreeting() {
        return "Hello World!";
    }

    public void createSomeBlocks() {
        addGenesisBlock("This is the first block");

		addBlock("This is the second block");

		addBlock("And this is the third block");

        String blockchainJson = new GsonBuilder().setPrettyPrinting().create().toJson(blockchain);
        System.out.println(blockchainJson);

        if (isChainValid()) 
            System.out.println("Chain is valid :)");
        else 
            System.out.println("Chain is invalid..");

    }

    public void addGenesisBlock(String data) {
        blockchain.add(new Block(data, "0"));
        System.out.println("Mining the genesis block");
        blockchain.get(blockchain.size() - 1).mine(DIFFICULTY);
    }

    public void addBlock(String data) {
        blockchain.add(new Block(data, blockchain.get(blockchain.size() - 1).hash));
        System.out.println("Mining the block #" + blockchain.size());
        blockchain.get(blockchain.size() - 1).mine(DIFFICULTY);
    }

    public boolean isChainValid() {
        Block currBlock;
        Block prevBlock;
        String hashTarget = new String(new char[DIFFICULTY]).replace('\0', '0');

        for (int i = 1; i < blockchain.size(); i++) {
            prevBlock = blockchain.get(i-1);
            currBlock = blockchain.get(i);

            // Verify current hash
            if (!currBlock.hash.equals(currBlock.calculateHash())) {
                System.out.println("Current hash for block:" + i + " does not match what it should be.");
                return false;
            }

            // Verify previous hash
            if (!prevBlock.hash.equals(currBlock.previousHash)) {
                System.out.println("Current block's previousHash does not match previous block's hash");
                return false;
            }

            //Verify hash has been solved
            if (!currBlock.hash.substring(0, DIFFICULTY).equals(hashTarget)) {
                System.out.println("This block has yet to be mined");
                return false;
            }

        }

        return true;
    }

    public static void main(String[] args) {
        ObsidianChain oc = new ObsidianChain();

        Security.addProvider(new org.bouncycastle.jce.provider.BouncyCastleProvider());

        walletA = new Wallet();
        walletB = new Wallet();

        System.out.println("Private and public keys: ");
        System.out.println("\t" + StringUtil.getStringFromKey(walletA.getPrivateKey()));
        System.out.println("\t" + StringUtil.getStringFromKey(walletA.getPublicKey()));

        Transaction transaction = new Transaction(walletA.getPublicKey(), walletB.getPublicKey(), 5, null);
        transaction.generateSignature(walletA.getPrivateKey());

        System.out.println("Is signature verified: " + transaction.verifySignature());



        System.out.println(oc.getGreeting());
        oc.createSomeBlocks();
    }
}
