/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.obsidianchain;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        ObsidianChain classUnderTest = new ObsidianChain();
        assertNotNull(classUnderTest.getGreeting(), "ObsidianChain should have a greeting");
    }
}
